name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lints Pull Request commits
        uses: wagoid/commitlint-github-action@v2

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Read node version from `.nvmrc` file
        id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.node_version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm dependencies
        run: npm install --progress=false --loglevel=warn --ignore-scripts

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Lint code
        run: npm run lint

      - name: Build dist
        run: npm run build:dist

      - name: Check build
        run: npm run typecheck

      - name: Run tests and covarage
        run: npm run coverage
